-- This migration was previously used to add a roles column but has been superseded
-- by proper JPA @ElementCollection mapping via the user_roles table.
-- Roles are now correctly managed through the user_roles junction table (V1 schema)
-- See User.java @ElementCollection for the correct mapping.